version: '3.1'

services:
  download_rar:
    build: .
    volumes:
      - ./fias_data:/data
    command: ["./app", "-download", "/data"]
  unarchive_rar:
    build: .
    volumes:
      - ./fias_data:/data
    command: ["./app", "-unarchive", "/data/fias.rar", "/data/fias"]
  import:
    build: .
    depends_on:
      - db
    volumes:
      - ./fias_data:/data
    command: ["./app", "-import", "/data/fias/"]
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./model/sql/ddl.sql:/docker-entrypoint-initdb.d/initdb.sql